version: '3'
services:
  receiver:
    build: ../Receiver/
    restart: always
    ports:
      - 8080:8080
  storage:
    build: ../storage/
    restart: always
    ports:
      - 8090:8090
  processing_service:
    depends_on: 
      - storage
    build: ../processing_service/
    restart: always
    # ports:
    #   - 8100
    network_mode: host
  audit:
    build: ../audit/
    restart: always
    ports:
      - 8110:8110


      # HOSTNAME: ec2-34-219-221-192.us-west-2.compute.amazonaws.com