version: '3'
services:
  receiver:
    build: ../Receiver/
    restart: always
    ports:
      - 8080:8080
    environment:
      KAFKA_DNS: ec2-34-219-242-0.us-west-2.compute.amazonaws.com
      TARGET_ENV: test
    volumes:
      - ./config/Receiver:/config
      - ./info/logs:/logs

  storage:
    build: ../storage/
    restart: always
    ports:
      - 8090:8090
    environment:
      KAFKA_DNS: ec2-34-219-242-0.us-west-2.compute.amazonaws.com
      TARGET_ENV: test
    volumes:
      - ./config/storage:/config
      - ./info/logs:/logs

  processing_service:
    depends_on: 
      - storage
    build: ../processing_service/
    restart: always
    ports:
      - 8100:8100
    environment:
      STORAGE_HOSTNAME: storage
      STORAGE_PORT: 8090
      TARGET_ENV: test
    volumes:
      - ./config/processing_service:/config
      - ./info/logs:/logs
      - processing-db:/data

  audit:
    build: ../audit/
    restart: always
    ports:
      - 8110:8110
    environment:
      KAFKA_DNS: ec2-34-219-242-0.us-west-2.compute.amazonaws.com
      TARGET_ENV: test
    volumes:
      - ./config/audit:/config
      - ./info/logs:/logs

  dashboard:
    build: ../Sample_Code/
    # image: dashboard
    ports:
      - "3000:3000"
    depends_on:
      - "processing_service"
      - "audit"
    environment:
      HOST_DNS: ec2-34-219-242-0.us-west-2.compute.amazonaws.com

volumes:
  processing-db:
