version: 1
datastore:
  user: "roots"
  password: NewPassword
  hostname: ${KAKFKA_DNS}
  port: 3306
  db: "auctiondb"
  retries: 6
events:
  max_retry: 4
  sleep: 4
  hostname: ${KAKFKA_DNS}
  port: 9092
  topic: events