version: 1
BID_URL:
  url: http://localhost:8090/bid
AUCTION_URL:
  url: http://localhost:8090/listItem
events:
  hostname: ec2-54-200-72-83.us-west-2.compute.amazonaws.com
  port: 9092
  topic: events
  max_retry: 5
  sleep: 10