# FROM python

# ENV FILESYSTEM_ROOT="/app"
# # ENV HOSTNAME = "ec2-34-219-221-192.us-west-2.compute.amazonaws.com"

# WORKDIR $FILESYSTEM_ROOT


# COPY requirements.txt requirements.txt
# RUN pip3 install -r requirements.txt

# COPY app.py ./

# # CMD ["flask","run"]
# CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]


# # f'{environ["FILESYSTEM_PORT"]}'
# # environ["FILESYSTEM_ROOT"]
FROM ubuntu
LABEL maintainer="xelchantiry@my.bcit.ca"

ENV FILESYSTEM_ROOT="/app"
# ENV STORAGE="http://172.17.0.2:8090"
# ENV HOSTNAME = "ec2-54-203-2-61.us-west-2.compute.amazonaws.com"

WORKDIR $FILESYSTEM_ROOT


RUN apt-get update -y && \
apt-get install -y python3 python3-pip
# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip3 install -r requirements.txt
COPY . /app

# RUN sed -i "s|localhost|$STORAGE|g" app_conf.yml

RUN python3 create_tables_mysql.py

ENTRYPOINT [ "python3" ]
CMD [ "app.py" ]